/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, BaseWalletLocked, AbstractAddress } from "fuels";
import { Interface, Contract } from "fuels";
import type {
  FactoryContractAbi,
  FactoryContractAbiInterface,
} from "../FactoryContractAbi";
const _abi = {
  types: [
    {
      typeId: 0,
      type: "()",
      components: [],
      typeParameters: null,
    },
    {
      typeId: 1,
      type: "b256",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 2,
      type: "enum Option",
      components: [
        {
          name: "None",
          type: 0,
          typeArguments: null,
        },
        {
          name: "Some",
          type: 3,
          typeArguments: null,
        },
      ],
      typeParameters: [3],
    },
    {
      typeId: 3,
      type: "generic T",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 4,
      type: "struct ContractId",
      components: [
        {
          name: "value",
          type: 1,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
  ],
  functions: [
    {
      inputs: [
        {
          name: "base_token",
          type: 1,
          typeArguments: null,
        },
        {
          name: "quote_token",
          type: 1,
          typeArguments: null,
        },
        {
          name: "id_address",
          type: 1,
          typeArguments: null,
        },
        {
          name: "owner",
          type: 1,
          typeArguments: null,
        },
      ],
      name: "add_ido",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "owner",
          type: 1,
          typeArguments: null,
        },
      ],
      name: "get_ido_by_admin",
      output: {
        name: "",
        type: 2,
        typeArguments: [
          {
            name: "",
            type: 1,
            typeArguments: null,
          },
        ],
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "base_token",
          type: 1,
          typeArguments: null,
        },
        {
          name: "quote_token",
          type: 1,
          typeArguments: null,
        },
      ],
      name: "get_ido_by_token",
      output: {
        name: "",
        type: 2,
        typeArguments: [
          {
            name: "",
            type: 1,
            typeArguments: null,
          },
        ],
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "template_ido_id",
          type: 1,
          typeArguments: null,
        },
      ],
      name: "initilize",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "owner",
          type: 1,
          typeArguments: null,
        },
        {
          name: "base_token",
          type: 1,
          typeArguments: null,
        },
        {
          name: "quote_token",
          type: 1,
          typeArguments: null,
        },
        {
          name: "pool",
          type: 1,
          typeArguments: null,
        },
      ],
      name: "remove_ido",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "old_owner",
          type: 1,
          typeArguments: null,
        },
        {
          name: "new_owner",
          type: 1,
          typeArguments: null,
        },
      ],
      name: "update_admin",
      output: {
        name: "",
        type: 2,
        typeArguments: [
          {
            name: "",
            type: 1,
            typeArguments: null,
          },
        ],
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
  ],
  loggedTypes: [
    {
      logId: 0,
      loggedType: {
        name: "",
        type: 4,
        typeArguments: [],
      },
    },
    {
      logId: 1,
      loggedType: {
        name: "",
        type: 1,
        typeArguments: null,
      },
    },
  ],
  messagesTypes: [],
  configurables: [],
};

export class FactoryContractAbi__factory {
  static readonly abi = _abi;
  static createInterface(): FactoryContractAbiInterface {
    return new Interface(_abi) as unknown as FactoryContractAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: BaseWalletLocked | Provider
  ): FactoryContractAbi {
    return new Contract(
      id,
      _abi,
      walletOrProvider
    ) as unknown as FactoryContractAbi;
  }
}
