/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, BaseWalletLocked, AbstractAddress } from "fuels";
import { Interface, Contract } from "fuels";
import type {
  SwapContractAbi,
  SwapContractAbiInterface,
} from "../SwapContractAbi";
const _abi = {
  types: [
    {
      typeId: 0,
      type: "()",
      components: [],
      typeParameters: null,
    },
    {
      typeId: 1,
      type: "(_, _)",
      components: [
        {
          name: "__tuple_element",
          type: 8,
          typeArguments: null,
        },
        {
          name: "__tuple_element",
          type: 8,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 2,
      type: "(_, _)",
      components: [
        {
          name: "__tuple_element",
          type: 3,
          typeArguments: null,
        },
        {
          name: "__tuple_element",
          type: 3,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 3,
      type: "b256",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 4,
      type: "enum Identity",
      components: [
        {
          name: "Address",
          type: 6,
          typeArguments: null,
        },
        {
          name: "ContractId",
          type: 7,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 5,
      type: "enum SwapError",
      components: [
        {
          name: "PlaceholderError",
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 6,
      type: "struct Address",
      components: [
        {
          name: "value",
          type: 3,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 7,
      type: "struct ContractId",
      components: [
        {
          name: "value",
          type: 3,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 8,
      type: "u64",
      components: null,
      typeParameters: null,
    },
  ],
  functions: [
    {
      inputs: [
        {
          name: "address_0",
          type: 7,
          typeArguments: null,
        },
        {
          name: "address_1",
          type: 7,
          typeArguments: null,
        },
      ],
      name: "initialize",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
    },
    {
      inputs: [],
      name: "deposit",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
    },
    {
      inputs: [
        {
          name: "amount",
          type: 8,
          typeArguments: null,
        },
        {
          name: "asset_id",
          type: 7,
          typeArguments: null,
        },
      ],
      name: "withdraw",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
    },
    {
      inputs: [
        {
          name: "to",
          type: 4,
          typeArguments: null,
        },
      ],
      name: "add_liquidity",
      output: {
        name: "",
        type: 8,
        typeArguments: null,
      },
    },
    {
      inputs: [
        {
          name: "to",
          type: 4,
          typeArguments: null,
        },
      ],
      name: "remove_liquidity",
      output: {
        name: "",
        type: 1,
        typeArguments: null,
      },
    },
    {
      inputs: [
        {
          name: "amount_0",
          type: 8,
          typeArguments: null,
        },
        {
          name: "amount_1",
          type: 8,
          typeArguments: null,
        },
      ],
      name: "swap",
      output: {
        name: "",
        type: 1,
        typeArguments: null,
      },
    },
    {
      inputs: [],
      name: "get_pair",
      output: {
        name: "",
        type: 2,
        typeArguments: null,
      },
    },
    {
      inputs: [],
      name: "get_reserve",
      output: {
        name: "",
        type: 1,
        typeArguments: null,
      },
    },
  ],
  loggedTypes: [
    {
      logId: 0,
      loggedType: {
        name: "",
        type: 5,
        typeArguments: [],
      },
    },
    {
      logId: 1,
      loggedType: {
        name: "",
        type: 5,
        typeArguments: [],
      },
    },
    {
      logId: 2,
      loggedType: {
        name: "",
        type: 5,
        typeArguments: [],
      },
    },
    {
      logId: 3,
      loggedType: {
        name: "",
        type: 5,
        typeArguments: [],
      },
    },
  ],
};

export class SwapContractAbi__factory {
  static readonly abi = _abi;
  static createInterface(): SwapContractAbiInterface {
    return new Interface(_abi) as unknown as SwapContractAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: BaseWalletLocked | Provider
  ): SwapContractAbi {
    return new Contract(
      id,
      _abi,
      walletOrProvider
    ) as unknown as SwapContractAbi;
  }
}
